prometheus:
  prometheusSpec:
    scrapeInterval: 30s
    scrapeTimeout: 10s
    evaluationInterval: 30s
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 50Gi
  service:
    type: LoadBalancer

grafana:
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    storageClassName: gp2

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 10Gi

#